sudo rm -rf work/product/app/By_3rd_HeytapIdProviderIndia
sudo rm -rf work/product/app/By_3rd_McsIndia
sudo rm -rf work/product/app/By_3rd_NearmeIndia
sudo rm -rf work/product/app/By_3rd_RoamingAppIndia
sudo rm -rf work/product/app/Chrome/Chrome.apk
sudo rm -rf work/product/app/Drive/Drive.apk
sudo rm -rf work/product/app/Duo/Duo.apk
sudo rm -rf work/product/app/Gmail2/Gmail2.apk
sudo rm -rf work/product/app/GoogleAssistant/GoogleAssistant.apk
sudo rm -rf work/product/app/GooglePayIndia/GooglePayIndia.apk
sudo rm -rf work/product/app/Maps/Maps.apk
sudo rm -rf work/product/app/Photos/Photos.apk
sudo rm -rf work/product/app/Videos/Videos.apk
sudo rm -rf work/product/app/YouTube/YouTube.apk
sudo rm -rf work/product/app/YTMusic/YTMusic.apk
sudo rm -rf work/product/priv-app/AndroidAutoStub/AndroidAutoStub.apk
sudo rm -rf work/product/priv-app/HotwordEnrollmentOKGoogleHEXAGON*
sudo rm -rf work/product/priv-app/Velvet/Velvet.apk
sudo rm -rf work/system_ext/priv-app/SetupWizard/SetupWizard.apk
sudo rm -rf work/system/app/ARCore_stub/ARCore_stub.apk
sudo rm -rf work/system/app/By_3rd_FBAppManagerOverSeas/By_3rd_FBAppManagerOverSeas.apk
sudo rm -rf work/system/app/By_3rd_FBAppManagerOverSeas/lib/arm64/libbsdiff-jni.so
sudo rm -rf work/system/app/By_3rd_FBAppManagerOverSeas/lib/arm64/libmemalign16.so
sudo rm -rf work/system/app/By_3rd_FBAppManagerOverSeas/lib/arm64/libmemalign16_cpp.so
sudo rm -rf work/system/app/By_3rd_FBAppManagerOverSeas/lib/arm64/libzstd-jni.so
sudo rm -rf work/system/app/By_3rd_NetflixActivationOverSeas/By_3rd_NetflixActivationOverSeas.apk
sudo rm -rf work/system/app/By_3rd_NetflixStubOverSeas/By_3rd_NetflixStubOverSeas.apk
sudo rm -rf work/system/app/By_3rd_PlayAutoInstallConfigOverSeas/By_3rd_PlayAutoInstallConfigOverSeas.apk
sudo rm -rf work/system/priv-app/By_3rd_FBInstallOverSeas/By_3rd_FBInstallOverSeas.apk
sudo rm -rf work/system/priv-app/By_3rd_FBServicesOverSeas/By_3rd_FBServicesOverSeas.apk
sudo rm -rf work/system/reserve/By_3rd_FacebookOverSeas/By_3rd_FacebookOverSeas.apk
sudo rm -rf work/system/reserve/By_3rd_InstagramOverSeas/By_3rd_InstagramOverSeas.apk
sudo rm -rf work/system/reserve/By_3rd_MaftPreloadManagerOverSeas/By_3rd_MaftPreloadManagerOverSeas.apk
sudo rm -rf work/system/reserve/By_3rd_MessengerOverSeas/By_3rd_MessengerOverSeas.apk
sudo rm -rf work/system/reserve/CanvasResources/CanvasResources.apk
sudo rm -rf work/system/reserve/OPBackupRestore/OPBackupRestore.apk
sudo rm -rf work/system/reserve/OPForum/OPForum.apk
sudo rm -rf work/system/reserve/OPIconpackOnePlusH2/OPIconpackOnePlusH2.apk
sudo rm -rf work/system/reserve/OPIconpackOnePlusO2/OPIconpackOnePlusO2.apk
sudo rm -rf work/system/reserve/OPNote/OPNote.apk
sudo rm -rf work/system/reserve/OPSoundRecorder/OPSoundRecorder.apk
sudo rm -rf work/system/reserve/OPWidget/OPWidget.apk
sudo rm -rf work/system/reserve/OnePlusPods/OnePlusPods.apk
sudo rm -rf work/system/reserve/Weather/Weather.apk
sudo rm -rf work/system/reserve/card/card.apk
sudo rm -rf work/system_ext/app/NFCTestMode/NFCTestMode.apk
sudo rm -rf work/system_ext/app/NFCTestMode/oat/arm64/NFCTestMode.odex
sudo rm -rf work/system_ext/app/NFCTestMode/oat/arm64/NFCTestMode.vdex
sudo rm -rf work/system_ext/app/NQNfcNci/NQNfcNci.apk
sudo rm -rf work/system_ext/app/NQNfcNci/lib/arm64/libsn100nfc_nci_jni.so
sudo rm -rf work/system_ext/app/NQNfcNci/oat/arm64/NQNfcNci.odex
sudo rm -rf work/system_ext/app/NQNfcNci/oat/arm64/NQNfcNci.vdex
sudo rm -rf work/system_ext/app/NVBackupUI/NVBackupUI.apk
sudo rm -rf work/system_ext/app/NVBackupUI/oat/arm64/NVBackupUI.odex
sudo rm -rf work/system_ext/app/NVBackupUI/oat/arm64/NVBackupUI.vdex
sudo rm -rf work/system_ext/app/OPBackup/OPBackup.apk
sudo rm -rf work/system_ext/app/OPBreathMode/OPBreathMode.apk
sudo rm -rf work/system_ext/app/OPDeskClock/OPDeskClock.apk
sudo rm -rf work/system_ext/app/OPGamingSpace/OPGamingSpace.apk
sudo rm -rf work/system_ext/app/OPWallpaperResources
sudo rm -rf work/system_ext/bin/hypnusd
sudo rm -rf work/system_ext/etc/init/hypnusd.rc
sudo rm -rf work/system_ext/priv-app/OPAccessoryFramework
sudo rm -rf work/system_ext/priv-app/OnePlusCamera
sudo rm -rf work/system_ext/priv-app/subsdm
sudo rm -rf work/system/reserve/By_3rd_AmazonShoppingIndia
sudo rm -rf work/system/reserve/By_3rd*
